@echo off
cd /d "E:\项目\公司\智欣联创\临时测试项目\AI 国际货运代理剧本杀\cargo-mystery(qwen3-coder-next-80b-fp8)"
move img_1.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_2.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_3.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_4.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_5.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_6.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_7.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_8.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_9.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_10.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_11.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_12.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_13.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_14.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_15.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_16.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_17.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_18.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_19.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_20.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_21.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_22.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_23.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_24.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_25.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_26.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_27.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_28.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_29.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_30.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_31.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_32.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_33.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_34.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_35.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_36.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_37.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_38.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_39.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_40.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_41.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_42.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_43.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_44.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_45.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_46.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_47.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_48.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_49.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_50.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_51.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_52.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_53.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_54.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_55.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_56.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_57.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
move img_58.png "reference\项目选择\剧本实操\任务卡\assets\slices\" 2>NUL
echo Done!
dir "reference\项目选择\剧本实操\任务卡\assets\slices\*.png"
